name: Release VSIX

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Build extension
        run: |
          yarn compile

      - name: Package VSIX (vsce)
        run: |
          npx --yes @vscode/vsce package

      - name: Create GitHub Release and upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
